/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.JFileChooser;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPSClient;

/**
 *
 * @author poncho
 */
public class FenetreAjoutPhoto extends javax.swing.JDialog {

  private File f ;
  
  private String nomPhoto ;
  
  private String nomF;
    public FenetreAjoutPhoto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNomPhoto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Choisir photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtNomPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomPhotoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom de la photo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomPhoto))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser chooser = new JFileChooser( new File("."));
        
        chooser.setDialogTitle("ouvrir une image");
        
        int reponse = chooser.showOpenDialog(this);
        
        if (reponse == JFileChooser.APPROVE_OPTION)
        {
            
             InputStream input = null;
           
                f = chooser.getSelectedFile();
                
                
               nomPhoto = f.getName() ;
                nomF = f.getAbsolutePath();
                
               
                txtNomPhoto.setText(nomPhoto);
                
                
                
                
                
     
            
          
        }
                                              

 
                                   

 
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {                                         
          FileInputStream input = null;
          try {
              input = new FileInputStream(nomF);
              
              
          } catch (FileNotFoundException ex) {
              Logger.getLogger(FenetreAjoutPhoto.class.getName()).log(Level.SEVERE, null, ex);
          }
          FTPSClient ftpClient = new FTPSClient();
          
            
          ftpClient.connect("iutdoua-samba.univ-lyon1.fr",990);
          ftpClient.login("p1422607", "44D4ad251301");
          
          System.out.println(ftpClient.getReplyString());
          
          
          
            ftpClient.setFileType(FTP.BINARY_FILE_TYPE);

    ftpClient.setFileTransferMode(FTP.BINARY_FILE_TYPE);
     ftpClient.enterLocalPassiveMode();
  
    String remote = "public_html/" + txtNomPhoto.getText() ;
    
    String test[] =  txtNomPhoto.getText().split("\\.") ;
    
    
    String nomPhotoBase = txtNomPhoto.getText().split("\\.")[0];
    
    
    System.out.println(nomPhotoBase) ;
    
    
    
          boolean done = ftpClient.storeFile(remote, input);
          input.close();
          
          if( done)
          {
              
              System.out.println("reussi");
              
              this.dispose();
          }
          else
          {
              System.out.println(ftpClient.getReplyString());
              this.dispose();
          }
          
          
         
      } catch (IOException ex) {
          Logger.getLogger(FenetreAjoutPhoto.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNomPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomPhotoActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNomPhoto;
    // End of variables declaration//GEN-END:variables

}